nfs:
    mount_opts: "vers=3"
    mkmnt: True
    persist_mount: True
    persist_unmount: False
    # Taken from old map.jinja, should work
    # for most Linux distributions:
    pkgs_server:
        - nfs-common
        - nfs-kernel-server
    pkgs_client:
        - nfs-common
    service_name: nfs-kernel-server
